app/models/recipe.rb
db/migrate/20250826022828_fix_foreign_keys.rb
db/schema.rb
db/seeds.rb

-seeds created
-adjusted foreign keys to match rails convention

Created seeds, and did minor adjustments to database foreign keys

---

app/assets/stylesheets/components/_banner.scss
app/assets/stylesheets/components/_index.scss
app/assets/stylesheets/config/_bootstrap_variables.scss
app/assets/stylesheets/config/_colors.scss
app/controllers/recipes_controller.rb
app/views/layouts/application.html.erb
app/views/recipes/show.html.erb
config/routes.rb

Created recipes show page

---

app/assets/stylesheets/components/_card.scss
app/assets/stylesheets/components/_index.scss
app/controllers/recipes_controller.rb
app/javascript/controllers/search_controller.js
app/views/recipes/_list.html.erb
app/views/recipes/index.html.erb
app/views/recipes/index.turbo_stream.erb
config/routes.rb

Added recipes index page

---

app/assets/stylesheets/components/_floatingButton.scss
app/assets/stylesheets/components/_index.scss
app/javascript/controllers/floating_button_controller.js
app/views/layouts/application.html.erb
app/views/shared/_floatingButton.html.erb

Added floating menu for navigation

Added floating menu for navigation

---

Gemfile
Gemfile.lock
app/assets/stylesheets/components/_badge.scss
app/assets/stylesheets/components/_index.scss
app/controllers/recipes_controller.rb
app/models/favorite.rb
app/models/recipe.rb
app/models/user.rb
app/views/recipes/_favorite_button.html.erb
app/views/recipes/_like_button.html.erb
app/views/recipes/like.turbo_stream.erb
app/views/recipes/show.html.erb
app/views/recipes/toggle_favorite.turbo_stream.erb
config/initializers/acts_as_favoritor.rb
config/routes.rb
db/migrate/20250826073920_acts_as_favoritor_migration.rb
db/migrate/20250826081159_acts_as_votable_migration.rb
db/schema.rb

Added favorite and like function to show recipe.

Added favorite and like function

---

Gemfile
Gemfile.lock
config/initializers/ruby_llm.rb

-Set up Ruby LLM Gem
-Still needs API Key in .env file

Set up Ruby LLM Gem

---

app/javascript/controllers/scan_new.js

-Possible fix for photo preview on Heroku
-Still working on local server

Possible fix for photo preview on Heroku

---

app/controllers/recipes_controller.rb

-Should generate a list of recipes that saves to the @scan

Created recipes#create

---

app/assets/stylesheets/components/_card.scss
app/controllers/recipes_controller.rb
app/javascript/controllers/search_controller.js
app/views/recipes/_favorite_button.html.erb
app/views/recipes/_like_button.html.erb
app/views/recipes/_list.html.erb
app/views/recipes/index.html.erb
app/views/recipes/index.turbo_stream.erb

Recipes style

---

app/assets/stylesheets/components/_floatingButton.scss
app/views/layouts/application.html.erb
app/views/shared/_floatingButton.html.erb

Changed style of floating button and the background color

Styles changed

---

db/migrate/20250827062753_add_ingredients_to_scans.rb
db/schema.rb

-Added Ingredients to Scans model

Added Ingredients to Scans

---

app/assets/stylesheets/components/_card.scss
app/views/recipes/_list.html.erb

Changed to show recipes with overflow-y (horizontally)

Changed recipes index partial

---

app/controllers/scans_controller.rb

-Smallest fix to get scan#create to work

Fixed the scans#create so that I can properly get the image

---

app/assets/stylesheets/components/_floatingButton.scss
app/assets/stylesheets/pages/_dashboard.scss
app/views/shared/_floatingButton.html.erb

Changed to make the floating button really round

Floating button

---

app/javascript/controllers/scan_new_controller.js
app/views/scans/new.html.erb

-Just changed controller to Stimulus syntax

Changed scan controller to a stimulus one

---

Gemfile
app/assets/stylesheets/recipes/_ingredients.scss
app/javascript/controllers/add_ingredient_controller.js
app/javascript/controllers/duration_controller.js
app/views/recipes/new.html.erb
db/schema.rb

Recipe form

---

app/assets/config/manifest.json

Changed app name

---

app/assets/stylesheets/components/_card.scss
app/javascript/controllers/floating_button_controller.js
app/models/recipe.rb
app/views/recipes/_list.html.erb
app/views/recipes/_review_offcanvas.html.erb
app/views/recipes/index.html.erb
app/views/recipes/show.html.erb
app/views/shared/_floatingButton.html.erb

Changed show card, button styles, removed search button, hide floating navigation menu items when clicking outside

Added rating to show card, some styles changes

---

app/assets/stylesheets/pages/_index.scss
app/assets/stylesheets/pages/_scan_show.scss
app/views/scans/show.html.erb

- Added some styling to the recipes scan page

Created show page for recipes after the scan

---

app/assets/stylesheets/devise/_login.scss
app/controllers/recipes_controller.rb
app/views/devise/sessions/new.html.erb

Changed some styles from login

Login changes

---

app/controllers/recipes_controller.rb

Corrected problem in prompt that wasnt filtering items

Changed prompt to use the params given

---

app/views/devise/shared/_ios_pwa_links.html.erb

Added file for ios

---

app/assets/stylesheets/pages/_dashboard.scss
app/views/pages/dashboard.html.erb

Small styling of dashboard

---

app/assets/stylesheets/recipes/_ingredients.scss
app/controllers/recipes_controller.rb
app/views/recipes/new.html.erb
app/views/recipes/show.html.erb

Recipe ingredients

---

Gemfile
app/jobs/image_generator_job.rb
app/models/recipe.rb
bin/jobs
config/application.rb
config/environments/production.rb
config/puma.rb
config/queue.yml
config/recurring.yml
db/migrate/20250901005630_install_solid_queue.rb
db/schema.rb
test/jobs/image_generator_job_test.rb

Create service for generating images for recipes BUT commented it because price is too high for each generated image with OpenAI

Created job for generating images for recipes

---

Gemfile
Gemfile.lock
app/controllers/recipes_controller.rb
app/jobs/image_generator_job.rb
app/models/recipe.rb
app/views/pages/dashboard.html.erb
app/views/recipes/_list.html.erb
app/views/recipes/show.html.erb
app/views/scans/show.html.erb
bin/jobs
config/application.rb
config/environments/production.rb
config/puma.rb
config/queue.yml
config/recurring.yml
db/queue_schema.rb

Added service to run pollination and attach photo to recipe.

Added service to run after creating recipe

---

Gemfile
app/controllers/reviews_controller.rb
app/models/review.rb
app/views/reviews/_review_form.html.erb
app/views/reviews/_review_list.html.erb

Added a photo upload option to reviews

---

app/javascript/controllers/review_photo_controller.js
app/views/reviews/_review_list.html.erb

-Please check this i worked hard on it

Created popup for review photos

---

db/migrate/20250902005914_add_filters_and_calories_to_recipes.rb
db/schema.rb

fixed migration syntax error

---

app/assets/stylesheets/recipes/_ingredients.scss
app/javascript/controllers/add_ingredient_controller.js

solved the ingredients position problem

solved the ingredients position problem
